name: learn-github-actions
on: [push]
jobs:
	validate:
		runs-on: ubuntu-latest
			steps:
				- name: Checkout develop
					  uses: actions/checkout@v2

				- name: SetUp PHP
					  uses: shivamathur/setup-php@v2
					  with:
						  tools: composer:v2
						  php:version: '7.4'